sampletest/myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='main'),
    path('item/<int:board_id>/', views.index_page, name='index_page'),
    path('rublic/<int:rublic_id>/', views.rublic_page, name='rublic_page'),
    path('add/', views.BbCreateView.as_view(), name='add'),
    path('update/<int:pk>', views.BbUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.BbDeleteView.as_view(), name='delete'),
]

sampletest/sampletest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetConfirmView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView

from django.shortcuts import redirect

from .captcha_form import CheckPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('bboard/', permanent=True)),
    path('captcha/', include('captcha.urls')),

    path('bboard/', include('myapp.urls')),

    path('accounts/login/', LoginView.as_view(next_page='myapp:main', extra_context={'captcha': CheckPasswordForm()}), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page="myapp:main"), name='logout'),
    
    path('accounts/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

sampletest/myapp/models.py
from django.db import models
from django.core import validators


class Bb(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    content = models.TextField(verbose_name='Описание')
    price = models.FloatField(verbose_name='Стоимость', 
                              validators=[validators.MinValueValidator(0, 'Цена не может быть меньше 0!')])
    published = models.DateTimeField(verbose_name='Дата публикации', auto_now_add=True, db_index=True)
    rublic = models.ForeignKey('Rublic', on_delete=models.PROTECT, null=True, verbose_name='Рубрика')

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published', 'title']

    def __str__(self):
        return f'{self.title}\n{self.price}'
    

class Rublic(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', db_index=True)

    class Meta:
        verbose_name_plural = 'Рубирики'
        verbose_name = 'Рубрика'
        ordering = ['name']

    def __str__(self):
        return self.name

sampletest/myapp/forms.py
from django.forms import ModelForm

from .models import Bb


class BbForm(ModelForm):
    class Meta:
        model = Bb
        fields = ('title', 'content', 'price', 'rublic')

sampletest/myapp/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db import models
from django.core.paginator import Paginator
#from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Bb, Rublic
from .forms import BbForm


def index(request):
    items = Bb.objects.all()
    rublics = Rublic.objects.all()
    paginator = Paginator(items, 3)
    number = request.GET.get('page', 1)
    page = paginator.get_page(number)
    return render(request, 'myapp/index.html', {'items':page, 'rublics': rublics})


def index_page(request, board_id):
    res = get_object_or_404(Bb, pk=board_id)
    return render(request, 'myapp/index_page.html', {'item':res, 'rublics': Rublic.objects.all()})


def rublic_page(request, rublic_id):
    cur_rublic = get_object_or_404(Rublic, pk=rublic_id)
    items = Bb.objects.filter(rublic=cur_rublic)
    rublics = Rublic.objects.all()
    paginator = Paginator(items, 3)
    page = paginator.page(request.GET.get('page', 1))
    return render(request, 'myapp/rublic_page.html', {'c_rublic':cur_rublic, 'items':page, 'rublics':rublics})


class BbCreateView(LoginRequiredMixin, CreateView):
    template_name = 'myapp/create.html'
    form_class = BbForm
    success_url = reverse_lazy('myapp:main')
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rublics'] = Rublic.objects.all()
        return context 
    

class BbUpdateView(LoginRequiredMixin, UpdateView):
    form_class = BbForm
    template_name = 'myapp/update.html'
    success_url = reverse_lazy('myapp:main')
    model = Bb

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rublics'] = Rublic.objects.all()
        return context 
    

class BbDeleteView(LoginRequiredMixin, DeleteView):
    model = Bb
    #form_kwargs = {'rublic_id':}
    #success_url = 'bboard/rublic/{rublic_id}'
    success_url = reverse_lazy('myapp:rublic_page', kwargs={'rublic_id': '{rublic_id}'})
    template_name = 'myapp/delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rublics'] = Rublic.objects.all()
        print(context)
        return context 
    
    def post(self, request, *args, **kwargs):
        print(self, request, kwargs, args, sep='\n')
        return super().post(request, *args, **kwargs)

sampletest/myapp/templates/layout/basic.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Категория: {{c_rublic.name}}{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'myapp/board.css' %}">
</head>
<body>
    <h1>{% block title_2 %}{% endblock %}</h1>
    <div class="left_block">
        <a class="changeable_in_blue" href="{% url 'myapp:main' %}">Главная</a><br>
        {% for i in rublics %}
        <a class="changeable_in_blue" href="{% url 'myapp:rublic_page' i.pk %}">{{i.name}}</a><br>
        {% endfor %}
        <a class="changeable_in_blue" href="{% url 'myapp:add' %}">Добавить объявление</a>
    </div>

    {% include "layout/user_info.html" %}

    <div class="main_cl">
        {% if items %}
            {% for i in items %}
            <div class="section">
                <h2><b><a href="{% url 'myapp:index_page' i.id %}">{{i.title}}</a></b></h2>
                <p>{{i.content}}</p>
                <p class="price"><b>{{i.price}} руб.</b></p>
                <hr>
                <p><a href="{% url 'myapp:rublic_page' i.rublic.pk %}">{{i.rublic.name}}</a></p>
                <p class="date">{{i.published|date:"d.m.Y H:i:s"}}</p>
            </div>
            {% endfor %}
        {% else %}
            <h2>Здесь объявлений пока нет<h2>
        {% endif %}
    </div>

    {% block paginator %}{% endblock paginator %}
</body>
</html>

sampletest/myapp/templates/layout/form_template.html
{% load static %}

<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} объявление</title>
    <link type="text/css" rel="stylesheet" href="{% static 'myapp/board.css' %}">
</head>
<body>
    <h1>{% block title_h1 %}{% endblock title_h1 %} элемента</h1>
    <div class="left_block">
        <a class="changeable_in_blue" href="{% url 'myapp:main' %}">Главная</a><br>
    </div>
     {% include "layout/user_info.html" %}
    <div class="d_form">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value={% block button %}{% endblock %}>
        </form>
    </div>
</body>
</html>

sampletest/myapp/templates/layout/paginator.html
<div class="right_block">
    {% if page.has_previous %}
        <a class="changeable_in_blue" href="?page={{ page.previous_page_number }}">&#60;</a>
    {% endif %}
    Страница {{ page.number }} из {{ page.paginator.num_pages }}
    {% if  page.has_next %}
        <a class="changeable_in_blue" href="?page={{ page.next_page_number }}">&#62;</a>
    {% endif %}
</div>

sampletest/myapp/templates/layout/password_template.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'myapp/board.css' %}">
</head>
<body>
    <h1>{% block header %}{% endblock header %}</h1>
    <div class="d_form">{% block content %}{% endblock content %}</div>
</body>
</html>

sampletest/myapp/templates/layout/user_info.html
<div class="right_block">
    {% if user.is_authenticated %}
        <p>Пользователь: <b>{{ user.username }}</b></p>
        <p><a class="changeable_in_blue" href="{% url 'logout' %}">Выход</a></p>
        {% if user.username == "admin" %}
            <p><b><a class="changeable_in_blue" href="http://127.0.0.1:8000/admin/">Go to admin-site</a></b></p>
        {% endif %}
    {% else %}
        <p>Пользователь: <b>гость</b></p>
        <p><a class="changeable_in_blue" href="{% url 'login' %}">Вход</a></p>
    {% endif %}
</div>

sampletest/myapp/templates/myapp/create.html
{% extends "layout/form_template.html" %}

{% block title%}Добавить{% endblock %}
{% block title_h1 %}Добавление{% endblock title_h1 %}
{% block button %}"Добавить"{% endblock %}

sampletest/myapp/templates/myapp/delete.html
{% extends "layout/form_template.html" %}

{% block title %}Удалить{% endblock title %}
{% block title_h1 %}Удаление{% endblock title_h1 %}
{% block button %}"Удалить"{% endblock button %}

sampletest/myapp/templates/myapp/index.html
{% extends "layout/basic.html" %}

{% block title %}Объявления{% endblock %}
{% block title_2 %}Объявления{% endblock %}
{% block paginator %}
{% include 'layout/paginator.html' with page=items%}
{% endblock paginator %}

sampletest/myapp/templates/myapp/index_page.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Объявление {{item.id}}</title>
    <link href="{% static 'myapp/board.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    <h1>{{item.title}}</h1>

    <div class="left_block">
        <a class="changeable_in_blue" href="{% url 'myapp:main' %}">Главная</a><br>
        {% for i in rublics %}
        <a class="changeable_in_blue" href="{% url 'myapp:rublic_page' i.pk %}">{{i.name}}</a><br>
        {% endfor %}
    </div>

     {% include "layout/user_info.html" %}

    <div class="main_cl">
        <p>{{item.content}}</p>
        <p class="price">{{item.price}}</p>
        <hr>
        <a href="{% url 'myapp:rublic_page' item.rublic.pk %}">{{item.rublic.name}}</a>
        <p class="date">{{item.published|date:"d.m.Y H:i:s"}}</p>
    </div>

    <div class="right_block">
        <p><a class="changeable_in_blue" href="{% url 'myapp:update' item.pk %}">Обновить</a><p>
        <p><a class="changeable_in_blue" href="{% url 'myapp:delete' item.pk %}">Удалить</a><p>
    </div>
</body>
</html>

sampletest/myapp/templates/myapp/rublic_page.html
{% extends 'layout/basic.html' %}

{% block title %}Категория: {{c_rublic.name}}{% endblock %}
{% block title_2 %}{{c_rublic.name}}{% endblock %}
{% block paginator %}
{% include 'layout/paginator.html' with page=items%}
{% endblock paginator %}

sampletest/myapp/templates/myapp/update.html
{% extends "layout/form_template.html" %}

{% block title%}Обновить{% endblock %}
{% block title_h1 %}Объявление{% endblock title_h1 %}
{% block button %}"Обновить"{% endblock %}